// <auto-generated />
using BlazorApp7.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp7.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220525131343_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorApp7.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "t be shock, awe, or any other strongly felt emotion. In these such situations one must exclaim 'Bruh!', typically in a low tone of voice. Typically only men will exclaim using the word 'bruh', however, the S.O.B. (Society of Bruh) is a progressive union full of verified gamer bros and care not whether man nor woman exclaims with the word 'bruh'.",
                            ImageUrl = "https://static.truckersmp.com/images/vtc/logo/21823.1594940844.png",
                            Price = 9.99m,
                            Title = "Ldssdabas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "ffdfdffdfd",
                            ImageUrl = "https://i1.sndcdn.com/artworks-WUn6AbCdLf93PTsy-G96wBw-t500x500.jpg",
                            Price = 9.99m,
                            Title = "Ate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ffdfd",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2N6mPp7pI4GYStZ1HR9RKsXsvdzr3GT8wXA&usqp=CAU",
                            Price = 9.99m,
                            Title = "Alio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
